# Generated by Django 3.0.2 on 2020-01-19 20:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('characters', '0014_auto_20190517_0558'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('verses', '0004_auto_20190219_0121'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('text', models.TextField(blank=True)),
                ('tags', models.CharField(blank=True, default='', max_length=255)),
                ('characters', models.ManyToManyField(to='characters.Character')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('verses', models.ManyToManyField(to='verses.Verse')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
