# Generated by Django 2.1.1 on 2018-09-30 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('verses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verse',
            name='slug',
        ),
    ]
