# Generated by Django 2.1.1 on 2019-01-27 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verses', '0002_remove_verse_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verse',
            name='created',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='verse',
            name='updated',
            field=models.DateTimeField(),
        ),
    ]
