# Generated by Django 2.1.1 on 2019-02-19 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verses', '0003_auto_20190127_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verse',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='verse',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
