# Generated by Django 2.1.1 on 2018-10-12 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0002_auto_20180920_0203'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='author',
            new_name='user',
        ),
    ]
