# Generated by Django 2.1.1 on 2018-11-28 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0003_auto_20181012_0157'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='about',
            new_name='description',
        ),
    ]
