# Generated by Django 2.1.1 on 2019-01-27 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0004_auto_20181128_0742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='page_name',
            field=models.SlugField(max_length=25, unique=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='tagline',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
    ]
