# Generated by Django 2.1.1 on 2019-03-17 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('verses', '0004_auto_20190219_0121'),
        ('characters', '0007_auto_20190219_0121'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('text', models.TextField()),
                ('tags', models.CharField(blank=True, default='', max_length=255)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='characters.Character')),
                ('verse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='character_notes', to='verses.Verse')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
