# Generated by Django 2.1.1 on 2019-03-25 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('verses', '0004_auto_20190219_0121'),
        ('characters', '0008_characternote'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.TextField(max_length=30)),
                ('value', models.TextField(max_length=100)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='characters.Character')),
                ('verse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='character_details', to='verses.Verse')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
