# Generated by Django 2.1.1 on 2019-03-25 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('verses', '0004_auto_20190219_0121'),
        ('characters', '0009_characterdetail'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CharacterDetail',
            new_name='CharacterTrait',
        ),
    ]
