# Generated by Django 2.1.1 on 2019-04-12 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0012_auto_20190326_0654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charactertrait',
            name='verses',
            field=models.ManyToManyField(blank=True, related_name='character_traits', to='verses.Verse'),
        ),
    ]
