# Generated by Django 2.1.1 on 2019-05-17 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0013_auto_20190412_1813'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='character',
            options={'ordering': ['page_name']},
        ),
    ]
