# Generated by Django 3.0.2 on 2020-10-27 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0014_auto_20190517_0558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='charactertrait',
            name='character',
        ),
        migrations.RemoveField(
            model_name='charactertrait',
            name='verses',
        ),
        migrations.DeleteModel(
            name='CharacterNote',
        ),
        migrations.DeleteModel(
            name='CharacterTrait',
        ),
    ]
