# Generated by Django 2.1.1 on 2019-04-12 18:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('characters', '0013_auto_20190412_1813'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('verses', '0004_auto_20190219_0121'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, default='Untitled', max_length=100)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='chats', to=settings.AUTH_USER_MODEL)),
                ('verse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='chats', to='verses.Verse')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('text', models.TextField()),
                ('icon', models.URLField(blank=True, default='')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='characters.Character')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='chats.Chat')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
