# Generated by Django 2.1.1 on 2019-05-10 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='description',
            new_name='caption',
        ),
    ]
