# Generated by Django 2.1.1 on 2019-05-11 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0013_auto_20190412_1813'),
        ('chats', '0002_auto_20190510_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='characters',
            field=models.ManyToManyField(related_name='chats', to='characters.Character'),
        ),
    ]
