# Generated by Django 2.1.1 on 2019-09-20 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0003_chat_characters'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='cover',
            field=models.URLField(blank=True, default=''),
        ),
    ]
