# Generated by Django 2.1.1 on 2019-10-24 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0004_chat_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='open',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
