# Generated by Django 2.1.1 on 2018-12-05 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icons', '0002_auto_20181205_0752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faceclaim',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
