# Generated by Django 2.1.1 on 2019-05-17 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icons', '0006_collection_icons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='title',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
