# Generated by Django 2.1.1 on 2018-09-30 22:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('verses', '0002_remove_verse_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, default='Untitled', max_length=255)),
                ('caption', models.CharField(blank=True, default='', max_length=255)),
                ('starter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='starters', to=settings.AUTH_USER_MODEL)),
                ('verse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='threads', to='verses.Verse')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
