# Generated by Django 2.1.1 on 2018-10-12 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0002_reply'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thread',
            old_name='starter',
            new_name='user',
        ),
    ]
