# Generated by Django 2.1.1 on 2019-01-27 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0003_auto_20181012_0204'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reply',
            options={'verbose_name_plural': 'Replies'},
        ),
    ]
