# Generated by Django 2.1.1 on 2019-01-27 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0004_auto_20190127_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='created',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='reply',
            name='updated',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='thread',
            name='created',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='thread',
            name='updated',
            field=models.DateTimeField(),
        ),
    ]
