# Generated by Django 3.0.2 on 2020-01-19 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0007_auto_20190219_0121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
