# Generated by Django 2.1.1 on 2019-10-05 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_postdraft'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='posts', to='characters.Character'),
        ),
    ]
