# Generated by Django 2.1.1 on 2019-10-08 01:24

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_auto_20191005_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='delta',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
