# Generated by Django 2.1.1 on 2019-10-14 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_remove_post_delta'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='delta',
            field=models.TextField(blank=True, default=''),
        ),
    ]
