# Generated by Django 2.1.1 on 2019-11-04 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_remove_post_delta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postdraft',
            name='user',
        ),
        migrations.DeleteModel(
            name='PostDraft',
        ),
    ]
